global:
  # Set the scrape interval to every 5 seconds. Default is every 1 minute.
  scrape_interval: 5s
  # Evaluate rules every 15 seconds. The default is every 1 minute.
  evaluation_interval: 15s
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  - job_name: "kafka"
    static_configs:
      - targets: [ "broker1:9998", "broker2:9999" ]
  - job_name: "kafka-lag-exporter"
    static_configs:
      - targets: [ "kafka-lag-exporter:8000" ]
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: hostname
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '${1}'
