{
 "title": "sandbox-kafka",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Messages In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_messagesin_total{topic=\"static.message.topic\"}"
    }
   ]
  },
  { "title": "Bytes IN/OUT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Bytes In",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_bytesin_total{topic=\"static.message.topic\"}"
    }
   ]
  },
  {
   "title": "Bytes Out",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_bytesout_total{topic=\"static.message.topic\"}"
    }
   ]
  }
 ]
}